### ISSUE TITLE
MathGlyph: Variable fonts loose carefully prepared stacked nodes

### ISSUE THREAD

**Issue by kateliev** [robotools/fontMath#232]
Hi `fontMath` team. I am having trouble with a variable font project that uses stacked nodes to keep compatibility across masters. Tracing the root of the problem I have arrived here. I've also heard colleagues complaining  about facing similar issues with their projects. Fiddling with the code I think I have found a civilized solution and I am offering it to you.

Fix utilizes simple name/tag technique to sort out the newly introduced nodes from `MathGlyphPen`, thus leaving stacked nodes intentionally made by the type designer alone.  

Problem first referred here: https://github.com/LettError/ufoProcessor/issues/35
I believe my issue is similar to: https://github.com/robotools/fontMath/issues/127
Please see the attached code: [mathGlyph.zip](https://github.com/robotools/fontMath/files/6227683/mathGlyph.zip)

**Comment by typemytype** [comment]
He Vassil

thanks for the proposal!

but I think it better to keep the current implementation and add a **strict** mode.

Strict mode would mean it fails whenever two glyphs are different in structure (contour compatibility), component, anchor, guidelines and other glyph attributes must also be compatible (like the current implementation)

glyph structures are the same when:

* both glyphs have the same amount of contours
* contours has the same amount of points
* contours have the same points sequences, order of on/off curves

I believe this would also fix your issue.

**Comment by LettError** [comment]
WIP, but here's a start https://github.com/robotools/fontMath/commit/149b1c8e71b59957a9890a114e986e0061f40ad5

* Add strict flag to MathGlyphPen. This suppresses adding on-point offcurves for line segments.
* Add strict flag to MathGlyph object.
* Add strict version of outline tests.

I need to do some more tests.

**Comment by kateliev** [comment]
Hey, thank you will give it a try right away :)

**Comment by benkiel** [comment]
Closed by #235
