### ISSUE TITLE
Should fontMath be Py3 only?

### ISSUE THREAD

**Issue by benkiel** [robotools/fontMath#243]
Seems like it is time.

**Comment by LettError** [comment]
Can we make a final release for 2.x?

**Comment by benkiel** [comment]
yes, we can. Really this is more about the test environments than anything else.

**Comment by benkiel** [comment]
Version 0.7.0 includes the fixes for angles and the `strict` handling, and doesn't change things that mean py3 is required. I'm going to push 0.8.0, which will be py3 only.

**Comment by benkiel** [comment]
Closed by version 0.8.0
