### ISSUE TITLE
factorAngle changes break makeinstancesufo tests

### ISSUE THREAD

**Issue by kaydeearts** [robotools/fontMath#250]
Hi there,
We noticed the fontMath 0.8.1 update [breaks some of our tests in the AFDKO](https://github.com/adobe-type-tools/afdko/pull/1389/checks?check_run_id=3104180730#step:11:304), specifically in our `makeinstancesufo` tool. It seems to be tied to [these changes in factorAngle](https://github.com/robotools/fontMath/pull/189/files#diff-f22e1d202d2e6282b0962ccc998e9913489ddec2c4af0388d6eaaad8cd2fa4e2). The new italicAngle values after this update are concerning to us; we're curious what the purpose of this change was.

**Here's an example:** 
files here: 
[input.zip](https://github.com/robotools/fontMath/files/6857836/input.zip)

`makeinstancesufo -d font.designspace -i 5 -n`
Running that will produce a `bold.ufo` instance
The italicAngle value here was previously `2`, now it's outputting `1.4430379746835442`:

```
     <key>italicAngle</key>
-    <integer>2</integer>
+    <real>1.4430379746835442</real>
     <key>openTypeHheaAscender</key> 
```
---
italicAngle value changes within our other tests were all similar:
```
    <key>italicAngle</key>
-   <integer>2</integer>
+   <real>0.082278481</real>
    <key>openTypeHheaAscender</key>
```
```
    <key>italicAngle</key>
-   <integer>2</integer>
+   <real>0.7341772152</real>
    <key>openTypeHheaAscender</key>
```
```
     <key>italicAngle</key>
-    <integer>2</integer>
+    <integer>0</integer>
     <key>openTypeHheaAscender</key>
```
```
    <key>italicAngle</key>
-   <integer>-180</integer>
+   <integer>0</integer>
    <key>postscriptBlueFuzz</key>
```

**Comment by benkiel** [comment]
Hey @kaydeearts, see the original issue for the thinking: https://github.com/robotools/fontMath/pull/189

Without digging into your test cases, it seems that the code is doing a better job, the last one you have, italic angle shouldn't be -180, 0 seems to be correct. I'm wondering if this is more a case of the test values reflecting the error in the code, not the new code being wrong.

**Comment by kaydeearts** [comment]
Hi @benkiel , thanks for your response! It was more of the other cases that were of concern, but we discussed it again today and looked into it more. After that, it became clearer to us so I'll close this issue now. Thanks again!

**Comment by benkiel** [comment]
@kaydeearts no problem, sorry for throwing your tests out of wack, but this does seem to be correct, previous behavior was incorrect.
